FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./apps/web/package.json ./apps/web/package.json
COPY ./apps/web/turbo.json ./apps/web/turbo.json


RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install
COPY ./apps/web ./apps/web


EXPOSE 3000
CMD ["pnpm", "run", "start:frontend"]