## build docker image
## build the docker image to docker hub
## ssh into vm and start the new image

name: Continuous Deployment Frontend
on:
  push:
    branches: [main]
    paths:
      - "apps/web"
      - "packages"
      - "docker/Dockerfile.frontend"
      - ".github/workflows/cd_frontend.yaml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.frontend
          push: true
          tags: utkarshsingh8871/excalidraw-frontend:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: Deploy code to vm
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@167.71.224.99 -t "
            docker stop excalidraw-frontend || true &&
            docker rm excalidraw-frontend || true &&
            docker run --name excalidraw-frontend \
              -d -p 3000:3000
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              utkarshsingh8871/excalidraw-frontend:${{ github.sha }}"
