## build docker image
## build the docker image to docker hub
## ssh into vm and start the new image

name: Continuous Deployment WS
on:
  push:
    branches: [main]
    paths:
      - 'apps/ws-backend'
      - 'packages'
      - 'docker/Dockerfile.ws'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.ws
          push: true
          tags: utkarshsingh8871/excalidraw-ws:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
      
      - name: Deploy code to VM
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh

          ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@167.71.224.99 -t "
            docker stop excalidraw-ws || true &&
            docker rm excalidraw-ws || true &&
            docker run --name excalidraw-ws \
              -d -p 8080:8080 \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              utkarshsingh8871/excalidraw-ws:${{ github.sha }}"
